services:
  test_db:
    image: postgres:18
    container_name: rag_test_db
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag
      POSTGRES_DB: rag_test
    ports:
      - "5433:5432"