"""change refresh token column to token_hash

Revision ID: 80bfe51e29c3
Revises: b2b891609cbf
Create Date: 2026-06-04 21:34:20.391317

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80bfe51e29c3"
down_revision: str | Sequence[str] | None = "b2b891609cbf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("refresh_tokens", sa.Column("token_hash", sa.String(length=64), nullable=False))
    op.drop_index(op.f("ix_refresh_tokens_token"), table_name="refresh_tokens")
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.drop_column("refresh_tokens", "token")
    op.alter_column("users", "tenant_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "users",
        "email",
        existing_type=sa.TEXT(),
        type_=sa.String(length=320),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=320),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column("users", "tenant_id", existing_type=sa.UUID(), nullable=True)
    op.add_column(
        "refresh_tokens",
        sa.Column("token", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.create_index(op.f("ix_refresh_tokens_token"), "refresh_tokens", ["token"], unique=True)
    op.drop_column("refresh_tokens", "token_hash")
    # ### end Alembic commands ###
